erDiagram
  schema_migrations {
    integer version PK
    timestamp inserted_at
  }
  transactions {
    uuid id PK
    uuid contract_id
    varchar name
    money_with_currency amount
    date creation_date
    date payment_date
    timestamp inserted_at
    timestamp updated_at
  }
  users {
    uuid id PK
    varchar email
    varchar hashed_password
    timestamp confirmed_at
    timestamp inserted_at
    timestamp updated_at
  }
  users_tokens {
    uuid id PK
    bytea token
    varchar context
    varchar sent_to
    uuid user_id
    timestamp inserted_at
  }
  equipment {
    uuid id PK
    uuid location_id
    varchar name
    varchar reference_number
    varchar serial_number
    varchar description
    date purchase_date
    date commission_date
    date decommission_date
    timestamp inserted_at
    timestamp updated_at
  }
  equipment_emails {
    uuid id PK
    uuid equipment_id
    uuid email_id
    timestamp inserted_at
    timestamp updated_at
  }
  equipment_fees {
    uuid id PK
    uuid equipment_id
    uuid fee_id
    timestamp inserted_at
    timestamp updated_at
  }
  equipment_notes {
    uuid id PK
    uuid equipment_id
    uuid note_id
    timestamp inserted_at
    timestamp updated_at
  }
  equipment_phones {
    uuid id PK
    uuid equipment_id
    uuid phone_id
    timestamp inserted_at
    timestamp updated_at
  }
  locations {
    uuid id PK
    uuid club_id
    varchar name
    varchar reference_number
    varchar description
    timestamp inserted_at
    timestamp updated_at
  }
  location_emails {
    uuid id PK
    uuid location_id
    uuid email_id
    timestamp inserted_at
    timestamp updated_at
  }
  location_fees {
    uuid id PK
    uuid location_id
    uuid fee_id
    timestamp inserted_at
    timestamp updated_at
  }
  location_notes {
    uuid id PK
    uuid location_id
    uuid note_id
    timestamp inserted_at
    timestamp updated_at
  }
  location_phones {
    uuid id PK
    uuid location_id
    uuid phone_id
    timestamp inserted_at
    timestamp updated_at
  }
  location_postal_addresses {
    uuid id PK
    uuid location_id
    uuid postal_address_id
    timestamp inserted_at
    timestamp updated_at
  }
  events {
    uuid id PK
    uuid club_id
    varchar name
    varchar reference_number
    varchar status
    varchar description
    integer minimum_participants
    integer maximum_participants
    integer minimum_age_in_years
    integer maximum_age_in_years
    varchar venue_type
    varchar venue_description
    timestamp inserted_at
    timestamp updated_at
  }
  event_departments {
    uuid id PK
    uuid event_id
    uuid department_id
    timestamp inserted_at
    timestamp updated_at
  }
  event_emails {
    uuid id PK
    uuid event_id
    uuid email_id
    timestamp inserted_at
    timestamp updated_at
  }
  event_equipment {
    uuid id PK
    uuid event_id
    uuid equipment_id
    timestamp inserted_at
    timestamp updated_at
  }
  event_fees {
    uuid id PK
    uuid event_id
    uuid fee_id
    timestamp inserted_at
    timestamp updated_at
  }
  event_groups {
    uuid id PK
    uuid event_id
    uuid group_id
    timestamp inserted_at
    timestamp updated_at
  }
  event_locations {
    uuid id PK
    uuid event_id
    uuid location_id
    timestamp inserted_at
    timestamp updated_at
  }
  event_notes {
    uuid id PK
    uuid event_id
    uuid note_id
    timestamp inserted_at
    timestamp updated_at
  }
  event_phones {
    uuid id PK
    uuid event_id
    uuid phone_id
    timestamp inserted_at
    timestamp updated_at
  }
  event_postal_addresses {
    uuid id PK
    uuid event_id
    uuid postal_address_id
    timestamp inserted_at
    timestamp updated_at
  }
  club_documents {
    uuid id PK
    varchar type
    uuid club_id
    uuid document_id
    timestamp inserted_at
    timestamp updated_at
  }
  contact_documents {
    uuid id PK
    varchar type
    uuid contact_id
    uuid document_id
    timestamp inserted_at
    timestamp updated_at
  }
  contract_documents {
    uuid id PK
    varchar type
    uuid contract_id
    uuid document_id
    timestamp inserted_at
    timestamp updated_at
  }
  department_documents {
    uuid id PK
    varchar type
    uuid department_id
    uuid document_id
    timestamp inserted_at
    timestamp updated_at
  }
  documents {
    uuid id PK
    varchar title
    varchar description
    varchar filename
    varchar content_type
    integer byte_size
    varchar storage_path
    varchar thumbnail_path
    varchar checksum
    varchar fulltext
    boolean locked
    boolean public
    timestamp deleted_at
    uuid club_id
    uuid uploaded_by_id
    timestamp inserted_at
    timestamp updated_at
  }
  document_comments {
    uuid id PK
    varchar comment
    uuid document_id
    uuid commented_by_id
    timestamp inserted_at
    timestamp updated_at
  }
  document_log_entries {
    uuid id PK
    varchar action
    jsonb changes
    jsonb extension_changes
    uuid document_id
    uuid changed_by_id
    timestamp inserted_at
    timestamp updated_at
  }
  equipment_documents {
    uuid id PK
    varchar type
    uuid equipment_id
    uuid document_id
    timestamp inserted_at
    timestamp updated_at
  }
  event_documents {
    uuid id PK
    varchar type
    uuid event_id
    uuid document_id
    timestamp inserted_at
    timestamp updated_at
  }
  group_documents {
    uuid id PK
    varchar type
    uuid group_id
    uuid document_id
    timestamp inserted_at
    timestamp updated_at
  }
  location_documents {
    uuid id PK
    varchar type
    uuid location_id
    uuid document_id
    timestamp inserted_at
    timestamp updated_at
  }
  fees {
    uuid id PK
    uuid club_id
    uuid subsidy_id
    uuid successor_id
    boolean is_general
    varchar type
    varchar name
    varchar reference_number
    varchar description
    money_with_currency amount
    money_with_currency amount_one_time
    boolean is_for_contact_group_contacts_only
    integer minimum_age_in_years
    integer maximum_age_in_years
    timestamp inserted_at
    timestamp updated_at
  }
  fee_internal_events {
    uuid id PK
    uuid fee_id
    uuid internal_event_id
    timestamp inserted_at
    timestamp updated_at
  }
  fee_notes {
    uuid id PK
    uuid fee_id
    uuid note_id
    timestamp inserted_at
    timestamp updated_at
  }
  forecasts {
    integer id PK
  }
  subsidies {
    uuid id PK
    uuid club_id
    varchar name
    varchar reference_number
    varchar description
    money_with_currency amount
    timestamp inserted_at
    timestamp updated_at
  }
  subsidy_internal_events {
    uuid id PK
    uuid subsidy_id
    uuid internal_event_id
    timestamp inserted_at
    timestamp updated_at
  }
  subsidy_notes {
    uuid id PK
    uuid subsidy_id
    uuid note_id
    timestamp inserted_at
    timestamp updated_at
  }
  contracts {
    uuid id PK
    uuid club_id
    uuid contact_id
    uuid fee_id
    date signing_date
    date start_date
    date first_billing_date
    date termination_date
    date archive_date
    timestamp inserted_at
    timestamp updated_at
  }
  clubs {
    uuid id PK
    uuid location_id
    varchar name
    varchar reference_number
    varchar description
    varchar website_url
    date foundation_date
    timestamp inserted_at
    timestamp updated_at
  }
  club_contracts {
    uuid id PK
    uuid club_id
    uuid contract_id
    timestamp inserted_at
    timestamp updated_at
  }
  club_emails {
    uuid id PK
    uuid club_id
    uuid email_id
    timestamp inserted_at
    timestamp updated_at
  }
  club_financial_data {
    uuid id PK
    uuid club_id
    uuid financial_data_id
    timestamp inserted_at
    timestamp updated_at
  }
  club_notes {
    uuid id PK
    uuid club_id
    uuid note_id
    timestamp inserted_at
    timestamp updated_at
  }
  club_phones {
    uuid id PK
    uuid club_id
    uuid phone_id
    timestamp inserted_at
    timestamp updated_at
  }
  departments {
    uuid id PK
    uuid club_id
    varchar name
    varchar reference_number
    varchar description
    date creation_date
    timestamp inserted_at
    timestamp updated_at
  }
  department_contracts {
    uuid id PK
    uuid department_id
    uuid contract_id
    timestamp inserted_at
    timestamp updated_at
  }
  department_emails {
    uuid id PK
    uuid department_id
    uuid email_id
    timestamp inserted_at
    timestamp updated_at
  }
  department_fees {
    uuid id PK
    uuid department_id
    uuid fee_id
    timestamp inserted_at
    timestamp updated_at
  }
  department_notes {
    uuid id PK
    uuid department_id
    uuid note_id
    timestamp inserted_at
    timestamp updated_at
  }
  department_phones {
    uuid id PK
    uuid department_id
    uuid phone_id
    timestamp inserted_at
    timestamp updated_at
  }
  groups {
    uuid id PK
    uuid department_id
    varchar name
    varchar reference_number
    varchar description
    date creation_date
    timestamp inserted_at
    timestamp updated_at
  }
  group_contracts {
    uuid id PK
    uuid group_id
    uuid contract_id
    timestamp inserted_at
    timestamp updated_at
  }
  group_emails {
    uuid id PK
    uuid group_id
    uuid email_id
    timestamp inserted_at
    timestamp updated_at
  }
  group_fees {
    uuid id PK
    uuid group_id
    uuid fee_id
    timestamp inserted_at
    timestamp updated_at
  }
  group_notes {
    uuid id PK
    uuid group_id
    uuid note_id
    timestamp inserted_at
    timestamp updated_at
  }
  group_phones {
    uuid id PK
    uuid group_id
    uuid phone_id
    timestamp inserted_at
    timestamp updated_at
  }
  contacts {
    uuid id PK
    uuid club_id
    varchar type
    varchar name
    varchar organization_name
    varchar organization_type
    varchar person_last_name
    varchar person_first_name_1
    varchar person_first_name_2
    varchar person_gender
    date person_birthday
    timestamp inserted_at
    timestamp updated_at
  }
  contact_emails {
    uuid id PK
    uuid contact_id
    uuid email_id
    timestamp inserted_at
    timestamp updated_at
  }
  contact_financial_data {
    uuid id PK
    uuid contact_id
    uuid financial_data_id
    timestamp inserted_at
    timestamp updated_at
  }
  contact_groups {
    uuid id PK
    uuid club_id
    timestamp inserted_at
    timestamp updated_at
  }
  contact_group_contacts {
    uuid id PK
    uuid contact_group_id
    uuid contact_id
    timestamp inserted_at
    timestamp updated_at
  }
  contact_notes {
    uuid id PK
    uuid contact_id
    uuid note_id
    timestamp inserted_at
    timestamp updated_at
  }
  contact_phones {
    uuid id PK
    uuid contact_id
    uuid phone_id
    timestamp inserted_at
    timestamp updated_at
  }
  contact_postal_addresses {
    uuid id PK
    uuid contact_id
    uuid postal_address_id
    timestamp inserted_at
    timestamp updated_at
  }
  emails {
    uuid id PK
    varchar type
    varchar address
    boolean is_main
    timestamp inserted_at
    timestamp updated_at
  }
  financial_data {
    uuid id PK
    uuid invoice_recipient_postal_address_id
    varchar type
    varchar direct_debit_account_holder
    varchar direct_debit_iban
    varchar direct_debit_institute
    varchar invoice_recipient
    varchar invoice_additional_information
    boolean is_main
    timestamp inserted_at
    timestamp updated_at
  }
  internal_events {
    uuid id PK
    date commission_date
    date archive_date
    boolean is_recurring
    varchar frequency
    integer interval
    timestamp inserted_at
    timestamp updated_at
  }
  notes {
    uuid id PK
    varchar content
    timestamp inserted_at
    timestamp updated_at
  }
  phones {
    uuid id PK
    varchar type
    varchar number
    boolean is_main
    timestamp inserted_at
    timestamp updated_at
  }
  postal_addresses {
    uuid id PK
    varchar street
    varchar street_number
    varchar street_additional_information
    varchar zipcode
    varchar city
    varchar country
    boolean is_main
    timestamp inserted_at
    timestamp updated_at
  }
  applicationroles {
    uuid id PK
    varchar name
    timestamp inserted_at
    timestamp updated_at
  }
  clubroles {
    uuid id PK
    varchar name
    timestamp inserted_at
    timestamp updated_at
  }
  departmentroles {
    uuid id PK
    varchar name
    timestamp inserted_at
    timestamp updated_at
  }
  userapplicationroles {
    uuid id PK
    uuid user_id
    uuid applicationrole_id
    timestamp inserted_at
    timestamp updated_at
  }
  userclubroles {
    uuid id PK
    uuid user_id
    uuid club_id
    uuid clubrole_id
    timestamp inserted_at
    timestamp updated_at
  }
  userdepartmentroles {
    uuid id PK
    uuid user_id
    uuid department_id
    uuid departmentrole_id
    timestamp inserted_at
    timestamp updated_at
  }
  applicationroles ||--|{ userapplicationroles : ""
  clubroles ||--|{ userclubroles : ""
  clubs ||--|{ club_contracts : ""
  clubs ||--|{ club_documents : ""
  clubs ||--|{ club_emails : ""
  clubs ||--|{ club_financial_data : ""
  clubs ||--|{ club_notes : ""
  clubs ||--|{ club_phones : ""
  clubs ||--|{ contact_groups : ""
  clubs ||--|{ contacts : ""
  clubs ||--|{ contracts : ""
  clubs ||--|{ departments : ""
  clubs ||--|{ documents : ""
  clubs ||--|{ events : ""
  clubs ||--|{ fees : ""
  clubs ||--|{ locations : ""
  clubs ||--|{ subsidies : ""
  clubs ||--|{ userclubroles : ""
  contact_groups ||--|{ contact_group_contacts : ""
  contacts ||--|{ contact_documents : ""
  contacts ||--|{ contact_emails : ""
  contacts ||--|{ contact_financial_data : ""
  contacts ||--|{ contact_group_contacts : ""
  contacts ||--|{ contact_notes : ""
  contacts ||--|{ contact_phones : ""
  contacts ||--|{ contact_postal_addresses : ""
  contacts ||--|{ contracts : ""
  contracts ||--|{ club_contracts : ""
  contracts ||--|{ contract_documents : ""
  contracts ||--|{ department_contracts : ""
  contracts ||--|{ group_contracts : ""
  contracts ||--|{ transactions : ""
  departmentroles ||--|{ userdepartmentroles : ""
  departments ||--|{ department_contracts : ""
  departments ||--|{ department_documents : ""
  departments ||--|{ department_emails : ""
  departments ||--|{ department_fees : ""
  departments ||--|{ department_notes : ""
  departments ||--|{ department_phones : ""
  departments ||--|{ event_departments : ""
  departments ||--|{ groups : ""
  departments ||--|{ userdepartmentroles : ""
  documents ||--o| club_documents : ""
  documents ||--o| contact_documents : ""
  documents ||--o| contract_documents : ""
  documents ||--o| department_documents : ""
  documents ||--|{ document_comments : ""
  documents ||--|{ document_log_entries : ""
  documents ||--o| equipment_documents : ""
  documents ||--o| event_documents : ""
  documents ||--o| group_documents : ""
  documents ||--o| location_documents : ""
  emails ||--|{ club_emails : ""
  emails ||--|{ contact_emails : ""
  emails ||--|{ department_emails : ""
  emails ||--|{ equipment_emails : ""
  emails ||--|{ event_emails : ""
  emails ||--|{ group_emails : ""
  emails ||--|{ location_emails : ""
  equipment ||--|{ equipment_documents : ""
  equipment ||--|{ equipment_emails : ""
  equipment ||--|{ equipment_fees : ""
  equipment ||--|{ equipment_notes : ""
  equipment ||--|{ equipment_phones : ""
  equipment ||--|{ event_equipment : ""
  events ||--|{ event_departments : ""
  events ||--|{ event_documents : ""
  events ||--|{ event_emails : ""
  events ||--|{ event_equipment : ""
  events ||--|{ event_fees : ""
  events ||--|{ event_groups : ""
  events ||--|{ event_locations : ""
  events ||--|{ event_notes : ""
  events ||--|{ event_phones : ""
  events ||--|{ event_postal_addresses : ""
  fees ||--|{ contracts : ""
  fees ||--|{ department_fees : ""
  fees ||--|{ equipment_fees : ""
  fees ||--|{ event_fees : ""
  fees ||--|{ fee_internal_events : ""
  fees ||--|{ fee_notes : ""
  fees ||--|{ fees : ""
  fees ||--|{ group_fees : ""
  fees ||--|{ location_fees : ""
  financial_data ||--|{ club_financial_data : ""
  financial_data ||--|{ contact_financial_data : ""
  groups ||--|{ event_groups : ""
  groups ||--|{ group_contracts : ""
  groups ||--|{ group_documents : ""
  groups ||--|{ group_emails : ""
  groups ||--|{ group_fees : ""
  groups ||--|{ group_notes : ""
  groups ||--|{ group_phones : ""
  internal_events ||--|{ fee_internal_events : ""
  internal_events ||--|{ subsidy_internal_events : ""
  locations ||--|{ clubs : ""
  locations ||--|{ equipment : ""
  locations ||--|{ event_locations : ""
  locations ||--|{ location_documents : ""
  locations ||--|{ location_emails : ""
  locations ||--|{ location_fees : ""
  locations ||--|{ location_notes : ""
  locations ||--|{ location_phones : ""
  locations ||--|{ location_postal_addresses : ""
  notes ||--|{ club_notes : ""
  notes ||--|{ contact_notes : ""
  notes ||--|{ department_notes : ""
  notes ||--|{ equipment_notes : ""
  notes ||--|{ event_notes : ""
  notes ||--|{ fee_notes : ""
  notes ||--|{ group_notes : ""
  notes ||--|{ location_notes : ""
  notes ||--|{ subsidy_notes : ""
  phones ||--|{ club_phones : ""
  phones ||--|{ contact_phones : ""
  phones ||--|{ department_phones : ""
  phones ||--|{ equipment_phones : ""
  phones ||--|{ event_phones : ""
  phones ||--|{ group_phones : ""
  phones ||--|{ location_phones : ""
  postal_addresses ||--|{ contact_postal_addresses : ""
  postal_addresses ||--|{ event_postal_addresses : ""
  postal_addresses ||--|{ financial_data : ""
  postal_addresses ||--|{ location_postal_addresses : ""
  subsidies ||--|{ fees : ""
  subsidies ||--|{ subsidy_internal_events : ""
  subsidies ||--|{ subsidy_notes : ""
  users ||--|{ document_comments : ""
  users ||--|{ document_log_entries : ""
  users ||--|{ documents : ""
  users ||--|{ userapplicationroles : ""
  users ||--|{ userclubroles : ""
  users ||--|{ userdepartmentroles : ""
  users ||--|{ users_tokens : ""
