////   Copyright (c) 2021-2022 Stefan Strecker
////
////   Licensed under the Apache License, Version 2.0 (the "License");
////   you may not use this file except in compliance with the License.
////   You may obtain a copy of the License at
////
////       http://www.apache.org/licenses/LICENSE-2.0
////
////   Unless required by applicable law or agreed to in writing, software
////   distributed under the License is distributed on an "AS IS" BASIS,
////   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
////   See the License for the specific language governing permissions and
////   limitations under the License.


Project Sportyweb {
  database_type: 'PostgreSQL'
  Note: 'very early draft ideas'
}



//// -- LEVEL 1
//// -- Tables and References

// ------------------------------------- Mitglied und Mitgliedsstatus

Enum geschlecht_kuerzel {
    m [note: 'männlich']
    w
    d
}

Enum mitglied_status {
    0 [note: 'Inaktiv']
    1 [note: 'Aktiv']
    2 [note: 'Ehrenmitglied']
}

Table mitglieder as M {
    mitglied_id UUID [pk]
    mitgliedsnummer varchar(255) [unique, not null, note: 'existierende mitgliedsnummer importieren oder neue generieren']
    nachname varchar(255) [not null] // aktueller Nachname, kann aus mehreren Wörtern bestehen 
//    geburtsnachname varchar(255) [not null, note: ''] // vormaliger Nachname; Sachverhalt zunächst ausgeklammert
    vorname1 varchar(255) [not null] // Rufname, siehe Wikipedia zu "Rufname" 
    vorname2 varchar(255) // optional 
    geburtsdatum date [not null]
    geschlecht geschlecht_kuerzel
//    ausweisdokumentnummer text
// simplifiziert; später komplexere Adressdatenhaltung
    wohnadresse_zeile1 text
    wohnadresse_strasse_hausnummer text
    wohnadresse_plz_ort text
    iban varchar(34) // Deutsche IBAN immer len=22 https://de.wikipedia.org/wiki/Internationale_Bankkontonummer
    email varchar(319) // Kann NULL sein; nicht alle Mitglieder haben E-Mail-Adresse (angegeben) See https://dba.stackexchange.com/questions/37014/in-what-data-type-should-i-store-an-email-address-in-database
    mitgliedstatus mitglied_status  
    datum_erstellt dateTime [not null, default: "GETUTCDATE()"]
    datum_modifiziert dateTime [not null]
}

// Table mitgliedstatus {
//   mitgliedstatus_id int [pk, increment]
//   statuskuerzel varchar(1)
//   statusbeschreibung text
// }
// [ref: > mitgliedsstatus.mitgliedsstatus_id]

// zu Nachname / Familienname aus Wikipedia:
// "Als Familienname gilt gemäß dem Bürgerlichen Gesetzbuch (BGB, in Kraft seit dem 1. Januar 1900) der Nachname, der als Folge der Abstammung von den Eltern auf die Kinder übergeht. Die Angabe des Geburtsnamens einer einzelnen Person (Beispiel: „geborene …“, „gebürtig …“; abgekürzt „geb.“) ist kein Bestandteil des Familiennamens, der von den Eltern auf die Kinder übergeht. Der Familienname kann aus mehreren Wörtern bestehen (Beispiele: „Breuer genannt Nattenkemper“, „Olde grote Beverborg“)."



// ------------------------------------- Uebungsleitung

// Table Uebungsleitung {}
// Rolle eines Mitglieds!
// synonym: Trainer (Fitness)
// relevant: Trainerscheine und Zertifikate

// Table Abteilungsleitung {}
// Rolle eines Mitglieds!

// Table Abteilung {}
// rekursive Beziehung für Unterabteilungen etc.
// alternativer Bezeichner: Untergliederung
// alternativer Bezeichner: Organisationseinheit
// alternativer Bezeichner: Vereinssparte

// Table Sportangebot {}
// Sportangebote werden NUR von Abteilungen angeboten?!

// Table Vereinssparte {}
// Sind Sportangebote unabhängig von Abteilungen / Sparten?